variable "project_id" {
  type    = string
  default = "strongsville-city-schools"
}
variable "region" {
  type    = string
  default = "us-central1"
}
variable "env" {
  type    = string
  default = "dev"
}
variable "name_prefix" {
  type    = string
  default = "finchat"
}

# --- Governance / ops --------------------------------------------------------
variable "privileged_group" {
  type        = string
  description = "Member allowed to read unmasked PII (e.g., group:fraud-ops@datadinosaur.com)."
  default     = ""
}
variable "masked_reader_member" {
  type        = string
  description = "Analyst-tier human granted maskedReader — sees NULL for PII_FINANCIAL (ADR-0019). Empty = only the anonymous SA is masked."
  default     = ""
}
variable "platform_admin_member" {
  type        = string
  description = "Platform Admin human granted dataplex.viewer to browse Data Products and request access. Empty = no grant."
  default     = ""
}
variable "notification_email" {
  type    = string
  default = ""
}

# --- Cost guardrails ---------------------------------------------------------
variable "enable_budget" {
  type    = bool
  default = false
}
variable "billing_account" {
  type    = string
  default = ""
}
variable "budget_amount_usd" {
  type    = number
  default = 25
}

# --- Enterprise toggles (default OFF -> near-zero cost) ----------------------
variable "enable_streaming_job" {
  type        = bool
  description = "Deploy persistent 24/7 Dataflow streaming job (enterprise). Off = on-demand."
  default     = false
}
variable "run_min_instances" {
  type        = number
  description = "Cloud Run min instances. 0 = scale-to-zero (sandbox)."
  default     = 0
}
variable "enable_api_gateway" {
  type        = bool
  description = "Deploy API Gateway (requires products/transactions/api/openapi.yaml from Increment 3)."
  default     = false
}
variable "enable_workflows" {
  type        = bool
  description = "Deploy loan Cloud Workflow (requires products/loans/workflow source from Increment 4)."
  default     = false
}

# --- Model Armor (LLM I/O screening) -----------------------------------------
variable "enable_model_armor" {
  type        = bool
  description = "Create a Model Armor template for agent prompt/response screening."
  default     = true
}
variable "enable_model_armor_floor" {
  type        = bool
  description = "Also create a project-level Model Armor floor setting (needs elevated perms)."
  default     = false
}

# --- Knowledge Catalog (Dataplex Universal Catalog) — ADR-0010 ---------------
variable "enable_catalog" {
  type        = bool
  description = "Deploy the Dataplex catalog overlay (aspect types, domain entry groups, DQ scans)."
  default     = false
}

# --- Custom domain -----------------------------------------------------------
variable "custom_domain" {
  type        = string
  description = "Map this domain to the UI Cloud Run service (e.g. finchat.datadinosaur.com). Empty = skip. Domain must be verified for the project first."
  default     = ""
}

variable "labels" {
  type    = map(string)
  default = { app = "finchat", managed_by = "terraform" }
}

variable "enable_bigtable" {
  type        = bool
  description = "Deploy the Bigtable hot-path serving tier (ADR-0017). No scale-to-zero (~$475/mo/node) — default off; develop against the emulator."
  default     = false
}

variable "enable_agent_harness" {
  type        = bool
  description = "Deploy the durable agent harness / reconciliation steward (ADR-0021): Cloud Run (scale-to-zero) + Cloud SQL Postgres. Cloud SQL has no scale-to-zero — default off; develop against a local Postgres."
  default     = false
}

# Generated by scripts/agents_catalog.py into agents.auto.tfvars.json — do not hand-edit.
# The agent catalogue is the source of truth; this is its Terraform projection.
variable "agents" {
  type = map(object({
    sa_key     = string
    display    = string
    owner      = string
    risk_tier  = string
    product    = string
    recert_due = string
  }))
  description = "Agent registry (ADR-0023), generated from scripts/agents_catalog.py."
  default     = {}
}

# --- Controls alerting (ADR-0026) --------------------------------------------
variable "servicenow_instance_url" {
  type        = string
  description = "ServiceNow instance for control-event notification (e.g. https://dev305242.service-now.com). Empty disables the notification path; the evidence sink is independent."
  default     = ""
}
variable "servicenow_user" {
  type        = string
  description = "ServiceNow integration user holding evt_mgmt_integration. Never an admin account."
  default     = "gcp_integration"
}
variable "controls_evidence_dataset" {
  type        = string
  description = "BigQuery dataset for the append-only control_events evidence table. Empty disables the evidence sink."
  default     = ""
}

variable "model_armor_use_dlp_templates" {
  type        = bool
  description = "Point Model Armor's SDP filter at the project's own DLP inspect/de-identify templates (advanced mode) instead of the built-in infoTypes. Adds DLP inspection billing per screened request."
  default     = false
}

variable "controls_chat_provider" {
  type        = string
  description = "Chat destination for control events: \"teams\", \"google_chat\", or \"\" for none."
  default     = ""
}

variable "mcp_client_service_accounts" {
  type        = list(string)
  description = <<-EOT
    Members granted roles/run.invoker on the MCP service (ADR-0031), as fully-qualified
    IAM members, e.g. "serviceAccount:ai-gateway-sa@PROJECT.iam.gserviceaccount.com".

    This is the whole access-control story for the MCP endpoint, so it is a variable
    rather than a hardcoded list: the consumers live in other repos and other teams, and
    the grant should be reviewable as configuration. Default empty — an MCP endpoint
    nobody can invoke is the right thing to ship by accident.
  EOT
  default     = []
}

variable "enable_mcp_oauth" {
  type        = bool
  description = <<-EOT
    Provision the OAuth proxy that hosted MCP clients need (ADR-0020).

    Off by default, and deliberately a separate decision from deploying the MCP server
    itself: this is the only publicly reachable service in the platform, and standing it
    up in an environment nobody is going to connect a hosted client to adds public
    surface for no benefit. Turning it on still leaves it refusing every identity until
    OAUTH_ALLOWED_DOMAINS and OAUTH_ALLOWED_RESOURCES are configured at deploy time.
  EOT
  default     = false
}

variable "mcp_public" {
  type        = bool
  description = <<-EOT
    Serve the MCP endpoint to the public internet, so hosted clients that cannot mint a
    Google OIDC token can reach it (ADR-0020).

    Off by default and NOT derived from the OAuth variables on purpose: opening this door
    should take two independent changes rather than one edit. It is only survivable when
    `FINCHAT_MCP_OAUTH_ISSUER` and `FINCHAT_MCP_RESOURCE` are set on the deploy, because
    turning this on removes Cloud Run IAM — the thing that has been authenticating the
    in-GCP callers all along — and leaves the server's own validation as the only gate.
  EOT
  default     = false
}

variable "enable_aws_mcp_client" {
  type        = bool
  description = <<-EOT
    Federate an AWS IAM role so a container there can call the MCP endpoint without a
    human completing the OAuth flow. Off by default: it creates a trust relationship with
    an external cloud account, which should never appear because a default said so.

    Turning it on also requires `aws_account_id` and `aws_mcp_client_role`, and the
    resulting service account must be added to FINCHAT_MCP_SERVICE_CALLERS *and the MCP
    service redeployed* — env vars bake at deploy time.
  EOT
  default     = false
}

variable "aws_account_id" {
  type        = string
  description = "The 12-digit AWS account allowed to federate. Only meaningful with enable_aws_mcp_client."
  default     = ""
  validation {
    condition     = var.aws_account_id == "" || can(regex("^[0-9]{12}$", var.aws_account_id))
    error_message = "aws_account_id must be 12 digits."
  }
}

variable "aws_mcp_client_role" {
  type        = string
  description = <<-EOT
    The AWS IAM ROLE NAME (not ARN) permitted to federate — e.g. "finchat-mcp-client".
    Named explicitly because an AWS account is an authentication boundary, not an
    authorization one: without this, every principal in the account could impersonate the
    service account.
  EOT
  default     = ""
}
