#!/usr/bin/env python3
"""Compile machine-readable facts from the OKF knowledge bundle into a committed
Python module (ui/_okf_context.py) consumed by the analyst grounding in ui/server.py.

The OKF bundle is the single source of truth. The structured `perimeter` and `joins`
frontmatter on the analyst playbooks generate BOTH the Conversational Analytics
semantic perimeter (the table allow-list) AND the join-model bullets injected into
the CA system instruction — so the prose prompt, the table list, and the human-readable
playbook can no longer drift apart.

The UI Cloud Run image copies only a handful of named files, so we compile to a plain
Python module at authoring time (committed) rather than parsing the bundle at runtime:
no new runtime dependency, no bundle shipped in the image.

    Run from the repo root:   python scripts/compile_okf.py
    Drift guard (CI):         ui/test_okf_context.py
"""
from __future__ import annotations

import json
import pathlib

import yaml  # build-time only; the generated module has no third-party imports.

ROOT = pathlib.Path(__file__).resolve().parents[1]
BUNDLE = ROOT / "knowledge"
OUT = ROOT / "ui" / "_okf_context.py"


def _frontmatter(path: pathlib.Path) -> dict:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise ValueError(f"{path}: missing YAML frontmatter")
    _, fm, _body = text.split("---", 2)  # body may contain '---'; maxsplit keeps it whole
    return yaml.safe_load(fm) or {}


def build() -> dict:
    """Parse the SSOT concepts into the values rendered into _okf_context.py."""
    perimeter = _frontmatter(BUNDLE / "playbooks" / "analyst-perimeter.md")["perimeter"]
    joins = _frontmatter(BUNDLE / "playbooks" / "analyst-join-paths.md")["joins"]
    bullets = "".join(
        f"- {j['from']}.{j['from_key']} = {j['to']}.{j['to_key']} ({j['rel']})\n"
        for j in joins
    )
    return {"perimeter": perimeter, "join_bullets": bullets}


def render(data: dict) -> str:
    return (
        '"""GENERATED by scripts/compile_okf.py from the OKF bundle in knowledge/.\n'
        "DO NOT EDIT BY HAND — run `python scripts/compile_okf.py` to regenerate.\n"
        "SSOT: knowledge/playbooks/analyst-perimeter.md + analyst-join-paths.md.\n"
        '"""\n'
        "from __future__ import annotations\n\n"
        f"ANALYST_PERIMETER = {json.dumps(data['perimeter'], indent=4)}\n\n"
        f"ANALYST_JOIN_BULLETS = {data['join_bullets']!r}\n"
    )


def main() -> None:
    OUT.write_text(render(build()), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
