#!/usr/bin/env python3
"""Compile machine-readable facts from the OKF knowledge bundle into a committed
Python module (ui/_okf_context.py) consumed by the analyst grounding in ui/server.py.

The OKF bundle is the single source of truth. The structured `perimeter` and `joins`
frontmatter on the analyst playbooks generate BOTH the Conversational Analytics
semantic perimeter (the table allow-list) AND the join-model bullets injected into
the CA system instruction — so the prose prompt, the table list, and the human-readable
playbook can no longer drift apart.

The UI Cloud Run image copies only a handful of named files, so we compile to a plain
Python module at authoring time (committed) rather than parsing the bundle at runtime:
no new runtime dependency, no bundle shipped in the image.

    Run from the repo root:   python scripts/compile_okf.py
    Drift guard (CI):         ui/test_okf_context.py
"""
from __future__ import annotations

import json
import pathlib

import compile_ontology  # sibling module in scripts/ (perimeter + join model SSOT)

ROOT = pathlib.Path(__file__).resolve().parents[1]
BUNDLE = ROOT / "knowledge"
OUT = ROOT / "ui" / "_okf_context.py"

# Descriptive concept docs (no runtime frontmatter to extract — plain semantics) that
# ground the analyst KB/semantics route. NOT playbooks (those compile to perimeter/joins)
# and NOT index.md (a manifest). Order is layer-by-layer for readable grounding.
CONCEPT_DIRS = ("datasets", "tables", "views", "metrics", "graph")


def _doc_body(path: pathlib.Path) -> str:
    """The prose of a concept doc, minus any leading YAML frontmatter."""
    text = path.read_text(encoding="utf-8")
    if text.startswith("---"):
        _, _fm, body = text.split("---", 2)
        return body.strip()
    return text.strip()


def _concept_corpus() -> str:
    """Concatenate the descriptive concept docs into one grounding blob. This is the
    large, static, text-only half of the bundle — meant to be prompt-cached at runtime,
    not turned into structured config like the perimeter."""
    parts = []
    for d in CONCEPT_DIRS:
        for md in sorted((BUNDLE / d).glob("*.md")):
            parts.append(f"### {d}/{md.name}\n{_doc_body(md)}")
    return "\n\n".join(parts)


def build() -> dict:
    """Project the ontology SSOT + concept docs into the values rendered into
    _okf_context.py. Perimeter and the join model come from knowledge/ontology.yaml
    (via compile_ontology); the knowledge corpus from the descriptive concept docs."""
    model = compile_ontology.load()
    return {
        "perimeter": compile_ontology.perimeter(model),
        "join_bullets": compile_ontology.join_bullets(model),
        "concept_corpus": _concept_corpus(),
    }


def render(data: dict) -> str:
    return (
        '"""GENERATED by scripts/compile_okf.py from the OKF bundle in knowledge/.\n'
        "DO NOT EDIT BY HAND — run `python scripts/compile_okf.py` to regenerate.\n"
        "SSOT: knowledge/playbooks/*.md (perimeter/joins) + knowledge/{datasets,tables,\n"
        "views,metrics,graph}/*.md (ANALYST_KNOWLEDGE concept corpus).\n"
        '"""\n'
        "from __future__ import annotations\n\n"
        f"ANALYST_PERIMETER = {json.dumps(data['perimeter'], indent=4)}\n\n"
        f"ANALYST_JOIN_BULLETS = {data['join_bullets']!r}\n\n"
        f"ANALYST_KNOWLEDGE = {data['concept_corpus']!r}\n"
    )


def main() -> None:
    # One command regenerates every ontology projection: the graph join view first,
    # then the OKF grounding module.
    compile_ontology.main()
    OUT.write_text(render(build()), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
