"""GENERATED by scripts/compile_okf.py from the OKF bundle in knowledge/.
DO NOT EDIT BY HAND — run `python scripts/compile_okf.py` to regenerate.
SSOT: knowledge/playbooks/analyst-perimeter.md + analyst-join-paths.md.
"""
from __future__ import annotations

ANALYST_PERIMETER = {
    "graph": [
        "dim_customer",
        "dim_account",
        "fact_transaction",
        "customer_360",
        "kg_relationships"
    ],
    "gold": [
        "overdraft_history"
    ],
    "loans": [
        "loan_status"
    ]
}

ANALYST_JOIN_BULLETS = '- dim_account.customer_id = dim_customer.customer_id (an Account BELONGS_TO a Customer)\n- fact_transaction.account_id = dim_account.account_id (a Transaction OCCURS_ON an Account)\n- overdraft_history.account_id = dim_account.account_id (an OverdraftProfile SUMMARIZES an Account)\n'
